name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install
    - run: npm run build
    - run: npm run map

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: build/CONTRIBUTORS.svg
        avatarSize: 42

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/create-tag-action@main
      with:
        package-path: package.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{ github.event.head_commit.message }}
        full_commit_message: ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      with:
        package-path: package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/ui-color/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  
          
          ${{ steps.changelog.outputs.changelog }}